using System;
namespace RawInput
{
	public enum MouseMessage : ulong
	{
		RI_MOUSE_LEFT_BUTTON_DOWN = 1uL,
		RI_MOUSE_LEFT_BUTTON_UP,
		RI_MOUSE_MIDDLE_BUTTON_DOWN = 16uL,
		RI_MOUSE_MIDDLE_BUTTON_UP = 32uL,
		RI_MOUSE_RIGHT_BUTTON_DOWN = 4uL,
		RI_MOUSE_RIGHT_BUTTON_UP = 8uL,
		RI_MOUSE_BUTTON_1_DOWN = 1uL,
		RI_MOUSE_BUTTON_1_UP,
		RI_MOUSE_BUTTON_2_DOWN = 4uL,
		RI_MOUSE_BUTTON_2_UP = 8uL,
		RI_MOUSE_BUTTON_3_DOWN = 16uL,
		RI_MOUSE_BUTTON_3_UP = 32uL,
		RI_MOUSE_BUTTON_4_DOWN = 64uL,
		RI_MOUSE_BUTTON_4_UP = 128uL,
		RI_MOUSE_BUTTON_5_DOWN = 256uL,
		RI_MOUSE_BUTTON_5_UP = 512uL,
		RI_MOUSE_WHEEL = 1024uL
	}
}
